 name: CI Build for Docker Action
 on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:
    
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        
      - name: Run Docker action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'Krishna'
          
      - name: Output time set in the container
        run: echo "The time of greeting was ${{ steps.hello-action.outputs.time }}"
